version: '3.8'

services:
  gct_postgres:
    image: postgres:latest
    container_name: gct_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chessrulz
      POSTGRES_DB: application
    ports:
      - '4675:5432'  # Exposing PostgreSQL to the host (optional)

  gct_api:
    image: aptacode/grand-chess-tree-api:0.0.1
    container_name: gct_api
    environment:
      ConnectionStrings__DefaultConnection: "Host=gct_postgres;Port=5432;Database=application;Username=postgres;Password=chessrulz"
    ports:
      - '8080:8080'
    depends_on:
      - gct_postgres
